### ISSUE TITLE
problem with tg and telegram-bot-lua

### ISSUE THREAD

**Issue by TeleSudo** [wrxck/telegram-bot-lua#12]
hi i use [tdbot.lua](https://github.com/rizaumami/tdbot.lua/) and [tg ](https://github.com/vysheng/tg) file to write a source . i want to use your lib for my soruce and send keyboard panel with lib and when i use api.run block tg and block receive message with tg and server cant read messages and dont answer to them but when i dont use api.run then your lib dont work and tg is ready and answering to all send messages.

[pic1](https://ibb.co/b7WsMjX) dont read messages
[pic2 ](https://ibb.co/k3SVNxQ)read message when api.run is off

**Comment by wrxck** [comment]
Please speak to the developer of tdbot
