### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by LetMyPplGo** [wrxck/telegram-bot-lua#14]
Hi!
Do you have plans to add windows support for your awesome project?

**Comment by wrxck** [comment]
Hey there! Windows support would rely on all of the libraries telegram-bot-lua uses to also have Windows support.
You could look into doing this manually using the [official guide to installing LuaRocks on Windows](https://github.com/luarocks/luarocks/wiki/installation-instructions-for-windows)
