### ISSUE TITLE
Problem on .configure(token)

### ISSUE THREAD

**Issue by arthurgsf** [wrxck/telegram-bot-lua#2]
this is what is printed in my terminal : 
Not Found [404]
lua: /usr/share/lua/5.3/telegram-bot-lua/core.lua:24: attempt to index a boolean value (field 'info')
stack traceback:
	/usr/share/lua/5.3/telegram-bot-lua/core.lua:24: in function 'telegram-bot-lua.core.configure'
	ufbot.lua:3: in main chunk
	[C]: in ?

by the way : ufbot is just the same as example.lua, i just added my bot token like 
 local api = require(telegram-bot-lua.core).configure(bot298319:AKjASdoAMnJkWyThjSfDg)

**Comment by wrxck** [comment]
1. You've left your bot token in the example.
2. You need to not include the "bot" part
3. It needs to be a string.

Like this: `local api = require(telegram-bot-lua.core).configure('298319:AKjASdoAMnJkWyThjSfDg')`
