### ISSUE TITLE
How can I disable a bot privacy mode?

### ISSUE THREAD

**Issue by italomaia** [wrxck/telegram-bot-lua#4]
I wish to have my bot talking with the other users like if it was one of them, without direct interaction. I saw some text explaining I had to disable privacy mode. Is it possible with this library?

**Comment by 4nt0n10M4** [comment]
If you mean what I think is deactivated like this:
1. Go to [BotFather](https://t.me/botfather) send `/setprivacy`.
2. Select the username of the bot.
3. Select `Disable`.

**Comment by italomaia** [comment]
Thanks @4nt0n10M4 it worked!

**Comment by wsdjeg** [comment]
Thanks, this is want I need.

**Comment by handlerug** [comment]
You can disable privacy mode for other bots by making them administrators of group. Try give @iftttbot admin permissions

**Comment by MartinDelille** [comment]
Despite making the @iftttbot admin permission, it still "has no access to message" in the group info panel.

**Comment by handlerug** [comment]
Hmm, it's strange. But why you need that permission? IFTTT works with his
command — try to look in their FAQ.

**Comment by MartinDelille** [comment]
Unfortunately I didn't found any info: the documentation is opaque I quit what I wanted to do :disappointed_relieved:
