### ISSUE TITLE
Tutorial on message types

### ISSUE THREAD

**Issue by italomaia** [wrxck/telegram-bot-lua#5]
Hello; is there a tutorial for the package? Like explaining when each type of message is used or with more examples? I would like to catch up with mattata source code after more "playing around".

**Comment by wrxck** [comment]
Hey - sorry again for the very late reply, I stopped development on this project but brought it back to life this year - I'm the sole developer of this API and I haven't had much in the way of making more examples - but I would be more than happy to add some if I get the chance!
